FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["AIos.Gateway/AIos.Gateway.csproj", "AIos.Gateway/"]
COPY ["AIos.Core/AIos.Core.csproj", "AIos.Core/"]
RUN dotnet restore "AIos.Gateway/AIos.Gateway.csproj"
COPY . .
WORKDIR "/src/AIos.Gateway"
RUN dotnet build "./AIos.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AIos.Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AIos.Gateway.dll"]
